//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 11. 11:20:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace TeamManagerContext
{
    public partial class Teams {

        public Teams()
        {
            this.Players = new List<Players>();
            this.Matches = new List<Matches>();
            this.Matches1 = new List<Matches>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string Region { get; set; }

        public virtual string League { get; set; }

        public virtual int? CoachId { get; set; }

        public string LogoURL { get; set; }


        public virtual IList<Players> Players { get; set; }


        public virtual Users Users { get; set; }


        public virtual IList<Matches> Matches { get; set; }


        public virtual IList<Matches> Matches1 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
