//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 09. 23:18:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace TeamManagerContext
{
    public partial class PlayerStats {

        public PlayerStats()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int MatchId { get; set; }

        public virtual int PlayerId { get; set; }

        public virtual double? KDA { get; set; }

        public virtual double? Score { get; set; }

        public virtual int? Form { get; set; }


        public virtual Matches Matches { get; set; }


        public virtual Players Players1 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
