//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 29. 18:34:29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace TeamManagerContext
{
    public partial class PlayerStats {

        public PlayerStats()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public int MatchId { get; set; }

        public int PlayerId { get; set; }

        public double KDA { get; set; }

        public double Score { get; set; }

        public int Form { get; set; }


        public virtual Matches Matches { get; set; }


        public virtual Players Players1 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
